update functionality and page done
cornellwebdev-admin/glue3-webdev pull request #32
Opened 2023-10-22 03:28 UTC by mikeyliang

2023-10-25 21:32 UTC, jay-joo-code requested changes
overall looks good!
just need to remove console logs

2023-10-25 21:32 UTC, jay-joo-code commented on src/routes/project/create/+page.svelte
> +		console.log(members);
let's remove console logs

2023-10-29 05:19 UTC, mikeyliang commented on src/routes/project/create/+page.svelte
> +		console.log(members);
okay!! 👍

2023-11-28 17:23 UTC, jay-joo-code submitted a review, later dismissed
looks good!

2024-03-18 14:50 UTC, jay-joo-code commented
@mikeyliang looks good!
just checking, currently how would a user edit their project? I'm not sure how they would be able to navigate to `/project/update/:projectID` path

2024-03-18 15:04 UTC, mikeyliang commented
> @mikeyliang looks good! just checking, currently how would a user edit their project? I'm not sure how they would be able to navigate to `/project/update/:projectID` path

I think in the menu they would be able to go to a profile page that has all their projects? Then each one of these projects links to a particular projectId, then redirect to /project/update/:projectID?

2024-03-18 16:02 UTC, jay-joo-code commented
> I think in the menu they would be able to go to a profile page that has all their projects? Then each one of these projects links to a particular projectId, then redirect to /project/update/:projectID? lmk what you think

Sounds good! Feel free to build what you think makes most sense. I just wanted to check in with you that that's not within the scope of this PR. 
This PR is already pretty big. Good work!

2024-03-18 16:34 UTC, merged